### ISSUE TITLE
possible a list of eggs only

### ISSUE THREAD

**Issue by kr4toos19** [srimko/axie-marketplace-watcher#1]
great project would be possible one only listing the newly posted eggs

**Comment by srimko** [comment]
Hello,

Now you can do it ;).

If you have other ideas I'll be happy to write some additional code.

**Comment by kr4toos19** [comment]
Hello,
it was very good congratulations

another ideals?

now what I think would be some method of filtering value, leaving the least values ​​always at the top

there's just this one, because your project is already very good
